apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: java-function
  namespace: default
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: java-function
spec:
  source:
    git:
      ref:
        branch: main
      url: https://github.com/tsalm-pivotal/functions-cnb-java-sample.git